### ISSUE TITLE
JDK15 Builds Broken

### ISSUE THREAD

**Issue by frank-dspeed** [direktspeed/graalvm-stack#9]
- https://github.com/oracle/graal/issues/2948#issuecomment-718993986

We Dounle the task and will pin last working version with new jdk 20.3-b03
GRAALVM-55b6687-GRAALJS-99c3e0c

**Comment by frank-dspeed** [comment]
``` 
Building gu.image... [dependency GRAALVM_18ADCA24E2_JAVA15_STAGE1 updated]
[gu:12158]    classlist:   2,846.69 ms,  0.96 GB
[gu:12158]        (cap):     754.67 ms,  0.96 GB
[gu:12158]        setup:   2,524.30 ms,  0.96 GB
[gu:12158]     (clinit):     333.34 ms,  2.39 GB
[gu:12158]   (typeflow):  18,840.25 ms,  2.39 GB
[gu:12158]    (objects):  28,815.83 ms,  2.39 GB
[gu:12158]   (features):     662.32 ms,  2.39 GB
[gu:12158]     analysis:  49,344.44 ms,  2.39 GB
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
	at parsing sun.nio.ch.DatagramChannelImpl.socket(DatagramChannelImpl.java:275)
Call path from entry point to sun.nio.ch.DatagramChannelImpl.socket(): 
	at sun.nio.ch.DatagramChannelImpl.socket(DatagramChannelImpl.java:272)
	at com.sun.jndi.dns.DNSDatagramSocketFactory.openRandom(DNSDatagramSocketFactory.java:230)
	at com.sun.jndi.dns.DNSDatagramSocketFactory.open(DNSDatagramSocketFactory.java:177)
	at com.sun.jndi.dns.DnsClient.getDatagramSocket(DnsClient.java:143)
	at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:403)
	at com.sun.jndi.dns.DnsClient.query(DnsClient.java:214)
	at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
	at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:129)
	at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:171)
	at sun.security.provider.certpath.ldap.LDAPCertStoreImpl$LDAPRequest.getValueMap(LDAPCertStoreImpl.java:308)
	at sun.security.provider.certpath.ldap.LDAPCertStoreImpl$LDAPRequest.getValues(LDAPCertStoreImpl.java:268)
	at sun.security.provider.certpath.ldap.LDAPCertStoreImpl.getCertificates(LDAPCertStoreImpl.java:415)
	at sun.security.provider.certpath.ldap.LDAPCertStoreImpl.getCertificates(LDAPCertStoreImpl.java:613)
	at sun.security.provider.certpath.ldap.LDAPCertStore.engineGetCertificates(LDAPCertStore.java:253)
	at java.security.cert.CertStore.getCertificates(CertStore.java:152)
	at sun.security.provider.certpath.PKIX$BuilderParams.getTargetSubject(PKIX.java:269)
	at sun.security.provider.certpath.PKIX$BuilderParams.checkParams(PKIX.java:231)
	at sun.security.provider.certpath.PKIX$BuilderParams.<init>(PKIX.java:219)
	at sun.security.provider.certpath.PKIX.checkBuilderParams(PKIX.java:69)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:125)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
	at sun.security.validator.Validator.validate(Validator.java:264)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:242)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	at sun.security.ssl.CertificateStatus$CertificateStatusConsumer.consume(CertificateStatus.java:295)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:207)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1491)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:894)
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1264)
	at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:268)
	at java.io.PrintStream.flush(PrintStream.java:423)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:2899)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findVarHandle(Class, String, Class): 
	no path found from entry point to target method


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

Building gu.image failed
1 build tasks failed
Error: Process completed with exit code 1.
```
